// DO NOT TOUCH THIS FILE. (Auto-generated by `keshvar-code-generator/src/countries.rs`)

//! A module for country `The Republic of Botswana`

#[cfg(all(feature = "bw", feature = "constants"))]
/// A module to access all constant country data for `The Republic of Botswana`.
///
/// Note that to use this module, `constant` feature should be enabled.
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, DistanceUnit, Region, SubRegion, WeekDay,
        WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::BW;
    pub const ALPHA3: Alpha3 = Alpha3::BWA;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 267;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::BWP;
    pub const GEC: Option<GEC> = Some(GEC::BC);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::BOT);
    pub const ISO_SHORT_NAME: &str = "Botswana";
    pub const ISO_LONG_NAME: &str = "The Republic of Botswana";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["en", "tn"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["en", "tn"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[7];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Motswana");
    pub const VEHICLE_REGISTRATION_CODE: Option<&str> = Some("RB");
    pub const NUMBER: &str = "072";
    pub const POSTAL_CODE: bool = false;
    pub const POSTAL_CODE_FORMAT: Option<&str> = None;
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::SouthernAfrica);
    pub const UN_LOCODE: &str = "BW";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Botswana", "ボツワナ"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    pub const G7_MEMBER: bool = false;
    pub const G20_MEMBER: bool = false;
    pub const EU_MEMBER: bool = false;
    pub const UN_MEMBER: bool = true;
    pub const EEA_MEMBER: bool = false;
    pub const DISTANCE_UNIT: DistanceUnit = DistanceUnit::Km;
    pub const POPULATION: Option<u64> = Some(2630296);
    #[cfg(feature = "emojis")]
    pub const EMOJI: &str = "🇧🇼";
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Botswana"),
        ("af", "Botswana"),
        ("ak", "Botswana"),
        ("am", "Botswana"),
        ("an", "Botswana"),
        ("ar", "بوتسوانا"),
        ("as", "বটছোৱ\u{9be}ন\u{9be}"),
        ("ay", "Botswana"),
        ("az", "Botsvana"),
        ("ba", "Botswana"),
        ("be", "Батсвана"),
        ("bg", "Ботсуана"),
        ("bi", "Botswana"),
        ("bn", "বোটসওয়\u{9be}ন\u{9be}"),
        ("bn_IN", "বোটসওয়\u{9be}ন\u{9be}"),
        ("br", "Botswana"),
        ("bs", "Bocvana"),
        ("ca", "Botswana"),
        ("ce", "Ботсвана"),
        ("ch", "Botswana"),
        ("cs", "Botswana"),
        ("cv", "Ботсвана"),
        ("cy", "Botswana"),
        ("da", "Botswana"),
        ("de", "Botsuana"),
        ("dv", "ބ\u{7ae}ޓ\u{7aa}ސ\u{7b0}ވ\u{7a7}ނ\u{7a7}"),
        ("dz", "བ\u{f71}\u{f7c}ཊས\u{f72}་ཝ་ན།"),
        ("ee", "Botswana"),
        ("el", "Μποτσουάνα"),
        ("en", "Botswana"),
        ("eo", "Bocvano"),
        ("es", "Botsuana"),
        ("et", "Botswana"),
        ("eu", "Botswana"),
        ("fa", "بوتسوانا"),
        ("ff", "Botswana"),
        ("fi", "Botswana"),
        ("fo", "Botsvana"),
        ("fr", "Botswana"),
        ("fy", "Botswana"),
        ("ga", "An Bhotsuáin"),
        ("gl", "Botsuana"),
        ("gn", "Botswana"),
        ("gu", "બોટ\u{acd}સ\u{acd}વાના"),
        ("gv", "Yn Votswaan"),
        ("ha", "Botswana"),
        ("he", "בוטסואנה"),
        ("hi", "बोत\u{94d}सवाना"),
        ("hr", "Bocvana"),
        ("ht", "Botswana"),
        ("hu", "Botswana"),
        ("hy", "Բոտսվանա"),
        ("ia", "Botswana"),
        ("id", "Botswana"),
        ("io", "Botswana"),
        ("is", "Botsvana"),
        ("it", "Botswana"),
        ("iu", "Botswana"),
        ("ja", "ボツワナ"),
        ("ka", "ბოტსვანა"),
        ("ki", "Botswana"),
        ("kk", "Ботсвана"),
        ("kl", "Botswana"),
        ("km", "ប\u{17bb}តស\u{17d2}វាណា"),
        ("kn", "ಬ\u{ccb}ಟ\u{ccd}ಸ\u{ccd}\u{200d}ವಾನಾ"),
        ("ko", "보츠와나"),
        ("ku", "Botswana"),
        ("kv", "Botswana"),
        ("kw", "Botswana"),
        ("ky", "Ботсвана"),
        ("lo", "Botswana"),
        ("lt", "Botsvana"),
        ("lv", "Botsvana"),
        ("mi", "Botswana"),
        ("mk", "Боцвана"),
        ("ml", "ബോട\u{d4d}സ\u{d4d}വ\u{d3e}ന"),
        ("mn", "Ботсвана"),
        ("mr", "बोस\u{94d}वाना"),
        ("ms", "Botswana"),
        ("mt", "Botswana"),
        (
            "my",
            "ဘော\u{1037}ဆ\u{103d}ာနာန\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Botwana"),
        ("nb", "Botswana"),
        ("ne", "बोट\u{94d}सवाना"),
        ("nl", "Botswana"),
        ("nn", "Botswana"),
        ("nv", "Tswana Dineʼé Bikéyah"),
        ("oc", "Botswana"),
        ("or", "ବୋସ\u{b4d}ତ\u{b4d}ବ\u{b3e}ନ\u{b3e}"),
        ("pa", "ਬ\u{a42}ਟਸਵਾਨਾ"),
        ("pi", "बोत\u{94d}सवाना"),
        ("pl", "Botswana"),
        ("ps", "بوتسوانا"),
        ("pt", "Botsuana"),
        ("pt_BR", "Botsuana"),
        ("ro", "Botswana"),
        ("ru", "Ботсвана"),
        ("rw", "Botswana"),
        ("sc", "Botswana"),
        ("sd", "Botswana"),
        ("si", "බොට\u{dca}ස\u{dca}ව\u{dcf}න\u{dcf}"),
        ("sk", "Botswana"),
        ("sl", "Bocvana"),
        ("so", "Botswana"),
        ("sq", "Botsvanë"),
        ("sr", "Боцвана"),
        ("sv", "Botswana"),
        ("sw", "Botswana"),
        ("ta", "போட\u{bcd}ஸ\u{bcd}வ\u{bbe}ன\u{bbe}"),
        ("te", "బ\u{c4b}స\u{c4d}వ\u{c3e}న\u{c3e}"),
        ("tg", "Ботсвана"),
        ("th", "บอตสวานา"),
        ("ti", "ቦትስዋና"),
        ("tk", "Botswana"),
        ("tl", "Botswana"),
        ("tr", "Botsvana"),
        ("tt", "Боцвана"),
        ("ug", "بوتسۋانا"),
        ("uk", "Ботсвана"),
        ("ur", "بوٹسوانا"),
        ("uz", "Botsvana"),
        ("ve", "Vhu-Tswana"),
        ("vi", "Bốt-xoă-na"),
        ("wa", "Boswana"),
        ("wo", "Botswana"),
        ("xh", "Botswana"),
        ("yo", "Bòtswánà"),
        ("zh_CN", "博兹瓦那"),
        ("zh_HK", "博茨瓦納"),
        ("zh_TW", "波札那"),
        ("zu", "IButswana"),
    ];
    #[cfg(all(feature = "bw", feature = "geo", feature = "constants"))]
    /// GEO data as constants
    pub mod geo {
        pub const LATITUDE: f64 = -22.328474;
        pub const LONGITUDE: f64 = 24.684866;
        pub const MAX_LATITUDE: f64 = -17.7781369;
        pub const MAX_LONGITUDE: f64 = 29.375304;
        pub const MIN_LATITUDE: f64 = -26.9075448;
        pub const MIN_LONGITUDE: f64 = 19.998903;
        pub const NORTHEAST_LATITUDE: f64 = -17.7781369;
        pub const NORTHEAST_LONGITUDE: f64 = 29.375304;
        pub const SOUTHWEST_LATITUDE: f64 = -26.9075448;
        pub const SOUTHWEST_LONGITUDE: f64 = 19.998903;
    }
}
#[cfg(all(feature = "bw", feature = "geo"))]
/// GEO module for this country.
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    /// GEO information for this country.
    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: -22.328474,
            longitude: 24.684866,
            max_latitude: -17.7781369,
            max_longitude: 29.375304,
            min_latitude: -26.9075448,
            min_longitude: 19.998903,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: -17.7781369,
                    longitude: 29.375304,
                },
                southwest: CountryGeoBound {
                    latitude: -26.9075448,
                    longitude: 19.998903,
                },
            },
        }
    }
}

#[cfg(all(feature = "bw", feature = "subdivisions"))]
/// Subdivision module for this country.
pub mod subdivisions {
    #[allow(unused_imports)]
    use crate::{Alpha2, Subdivision, SubdivisionType};
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::SubdivisionGeo;

    /// Subdivisions for this country.
    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from(
            [

                (
                    "CE",
                    Subdivision{
                        name: "Central",
                        country_alpha2: Alpha2::BW,
                        code: "CE",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-21.1672276), longitude: Some(26.419389), max_latitude: Some(-19.0024569), min_latitude: Some(-23.956503), max_longitude: Some(29.3607809), min_longitude: Some(23.885815)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Sentraal distrik, Botswana"), ("ar", "المقاطعة المركزية"), ("be", "Цэнтральная акруга, Батсвана"), ("bg", "Централна област"), ("bn", "সেন\u{9cd}ট\u{9cd}র\u{9be}ল জেল\u{9be}"), ("ca", "Districte Central"), ("ccp", "𑄥𑄬𑄚\u{11134}𑄑\u{11133}𑄢𑄣\u{11134}"), ("ceb", "Central District (distrito sa Botswana)"), ("da", "Central District"), ("de", "Central District"), ("el", "Κεντρική Περιφέρεια"), ("en", "Central"), ("es", "Distrito Central"), ("eu", "Erdialdea"), ("fa", "بخش مرکزی (بوتسوانا)"), ("fi", "Central District"), ("fr", "District Central"), ("gu", "સ\u{ac7}ન\u{acd}ટ\u{acd}રલ જિલ\u{acd}લો"), ("hi", "मध\u{94d}य जिला (इज\u{93c}राइल)"), ("hy", "Կենտրոնական շրջան"), ("id", "Distrik Central"), ("it", "distretto Centrale"), ("ja", "セントラル地区"), ("ka", "ცენტრალური ოლქი"), ("kn", "ಕ\u{cc7}ಂದ\u{ccd}ರ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "중부 구"), ("lt", "Centrinis rajonas"), ("lv", "Centrālais distrikts"), ("mk", "Централен округ"), ("mr", "मध\u{94d}यवर\u{94d}ती जिल\u{94d}हा"), ("ms", "Central District"), ("nb", "Central"), ("nl", "Central"), ("no", "Central"), ("pl", "Dystrykt Centralny"), ("pt", "Central"), ("ro", "Districtul Central, Botswana"), ("ru", "Центральный округ"), ("si", "මධ\u{dca}\u{200d}යම ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Central"), ("sw", "Wilaya ya Central (Botswana)"), ("ta", "சென\u{bcd}ட\u{bcd}ரல\u{bcd} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "స\u{c46}ంట\u{c4d}రల\u{c4d} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เซ\u{e47}นทร\u{e31}ล ด\u{e34}สทร\u{e34}ค"), ("tr", "Merkez Bölgesi"), ("uk", "Центральний округ"), ("ur", "وسطی ضلع"), ("vi", "Quận Miền Trung"), ("zh", "中部區"), ("zu", "Central District, Butswana")]),
                        unofficial_name_list: ["Central"].to_vec(),
                    }
                ),
                (
                    "CH",
                    Subdivision{
                        name: "Chobe",
                        country_alpha2: Alpha2::BW,
                        code: "CH",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Chobedistrik"), ("ccp", "𑄇\u{1112e}𑄝𑄬"), ("de", "Chobe District"), ("en", "Chobe"), ("es", "Distrito Chobe"), ("fa", "ناحیه چوبه"), ("fr", "Chobe"), ("id", "Distrik Chobe"), ("it", "Distretto di Chobe"), ("ja", "チョベ地区"), ("nb", "Chobe"), ("no", "Chobe"), ("pt", "Chobe"), ("ru", "Чобе"), ("sv", "Chobe"), ("ur", "چوبے ضلع"), ("zh", "乔贝区")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "FR",
                    Subdivision{
                        name: "Francistown",
                        country_alpha2: Alpha2::BW,
                        code: "FR",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::City,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Francistown"), ("ar", "فرانسيس"), ("az", "Frensistaun"), ("be", "Горад Франсістаўн"), ("bg", "Франсистаун"), ("bn", "ফ\u{9cd}র\u{9be}ঞ\u{9cd}চিসট\u{9be}উন"), ("ca", "Francistown"), ("ccp", "𑄜\u{11133}𑄢𑄚\u{11134}𑄥\u{11128}𑄌\u{11134}𑄑𑄅\u{1112a}𑄚\u{11134}"), ("ceb", "Francistown"), ("cs", "Francistown"), ("da", "Francistown"), ("de", "Francistown"), ("el", "Φράνσισταουν"), ("en", "Francistown"), ("es", "Francistown"), ("et", "Francistown"), ("eu", "Francistown"), ("fa", "فرانسیستوون، بوتسوانا"), ("fi", "Francistown"), ("fr", "Francistown"), ("gu", "ફ\u{acd}રાન\u{acd}સિસટાઉન"), ("he", "פרנסיסטאון"), ("hi", "फ\u{94d}रा\u{902}सिसटाउन"), ("hr", "Francistown"), ("hy", "Ֆրանսիսթաուն"), ("id", "Francistown"), ("it", "Francistown"), ("ja", "フランシスタウン"), ("ka", "ფრანსისთაუნი"), ("kn", "ಫ\u{ccd}ರಾನ\u{ccd}ಸ\u{cbf}ಸ\u{ccd}ಟ\u{ccc}ನ\u{ccd}"), ("ko", "프랜시스타운"), ("lt", "Frensistaunas"), ("lv", "Frensistauna"), ("mk", "Франсистаун"), ("mr", "फ\u{94d}र\u{945}न\u{94d}सिसटाउन"), ("ms", "Francistown"), ("nb", "Francistown"), ("nl", "Francistown"), ("no", "Francistown"), ("pl", "Francistown"), ("pt", "Francistown"), ("ro", "Francistown"), ("ru", "Франсистаун"), ("si", "ෆ\u{dca}\u{200d}රැන\u{dca}ස\u{dd2}ස\u{dca}ටව\u{dd4}න\u{dca}"), ("sr", "Франсистаун"), ("sr_Latn", "Fransistaun"), ("sv", "Francistown"), ("ta", "பிர\u{bbe}ன\u{bcd}ச\u{bc0}ஸ\u{bcd}நகரம\u{bcd}"), ("te", "ఫ\u{c4d}ర\u{c3e}న\u{c4d}స\u{c3f}స\u{c4d}\u{200c}ట\u{c4c}న\u{c4d}"), ("th", "แฟรนซ\u{e34}สทาวน\u{e4c}"), ("tr", "Francistown"), ("uk", "Франсистаун"), ("ur", "فرانسس ٹاؤن"), ("vi", "Francistown"), ("zh", "弗朗西斯敦")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "GA",
                    Subdivision{
                        name: "Gaborone",
                        country_alpha2: Alpha2::BW,
                        code: "GA",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::City,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Gaborone"), ("am", "ጋበሮኔ"), ("ar", "جابورون"), ("az", "Qaborone"), ("be", "Горад Габаронэ"), ("bg", "Габороне"), ("bn", "গ\u{9cd}য\u{9be}বোরোন"), ("bs", "Gaborone"), ("ca", "Gaborone"), ("ccp", "𑄉\u{11133}𑄠𑄝\u{11127}𑄢\u{11127}𑄚\u{11134}"), ("ceb", "Gaborone"), ("cs", "Gaborone"), ("cy", "Gaborone"), ("da", "Gaborone"), ("de", "Gaborone"), ("el", "Γκαμπορόνε"), ("en", "Gaborone"), ("es", "Gaborone"), ("et", "Gaborone"), ("eu", "Gaborone"), ("fa", "گابورون"), ("fi", "Gaborone"), ("fr", "Gaborone"), ("ga", "Gaborone"), ("gl", "Gaborone"), ("gu", "ગ\u{ac5}બરોન"), ("ha", "Gaborone"), ("ha_NE", "Gaborone"), ("he", "גאבורון"), ("hi", "गोबोर\u{94d}नी"), ("hr", "Gaborone"), ("hu", "Gaborone"), ("hy", "Գաբորոնե"), ("id", "Gaborone"), ("is", "Gaboróne"), ("it", "Gaborone"), ("ja", "ハボローネ"), ("jv", "Gaborone"), ("ka", "გაბორონე"), ("kn", "ಗ\u{cc6}ಬರ\u{ccb}ನ\u{ccd}"), ("ko", "가보로네"), ("ky", "Габороне"), ("lt", "Gaboronas"), ("lv", "Gaborone"), ("mk", "Габороне"), ("ml", "ഗ\u{d3e}ബറോൺ"), ("mn", "Габороне"), ("mr", "ग\u{945}बारोनी"), ("ms", "Gaborone"), ("my", "ဂါဘ\u{102d}\u{102f}ရ\u{102d}\u{102f}နေမြ\u{102d}\u{102f}\u{1037}"), ("nb", "Gaborone"), ("nl", "Gaborone"), ("no", "Gaborone"), ("pa", "ਗਾਬ\u{a4b}ਰ\u{a4b}ਨੀ"), ("pl", "Gaborone"), ("ps", "ګابورون"), ("pt", "Gaborone"), ("ro", "Gaborone"), ("ru", "Габороне"), ("si", "ගැබරෝන\u{dca}"), ("sk", "Gaborone"), ("sl", "Gaborone"), ("so", "Gaborone"), ("sq", "Gaborone"), ("sr", "Габороне"), ("sr_Latn", "Gaborone"), ("sv", "Gaborone"), ("sw", "Gaborone"), ("ta", "க\u{bbe}பரோனி"), ("te", "గ\u{c3e}బర\u{c4b}న\u{c46}"), ("th", "กาโบโรเน"), ("tk", "Gabaron"), ("tr", "Gaborone"), ("uk", "Габороне"), ("ur", "گبرون"), ("uz", "Gaborone"), ("vi", "Gaborone"), ("yo", "Gaborone"), ("yo_BJ", "Gaborone"), ("yue", "嘉波隆里"), ("yue_Hans", "嘉波隆里"), ("zh", "嘉柏隆里"), ("zu", "IGaborone")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "GH",
                    Subdivision{
                        name: "Ghanzi",
                        country_alpha2: Alpha2::BW,
                        code: "GH",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-21.698306), longitude: Some(21.64872), max_latitude: Some(-21.6784066), min_latitude: Some(-21.7141347), max_longitude: Some(21.6658974), min_longitude: Some(21.6237544)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Ghanzi distrik"), ("ar", "مقاطعةغانزي"), ("be", "Акруга Ганзі"), ("bg", "Ганзи"), ("bn", "গ\u{9be}ঞ\u{9cd}জি জেল\u{9be}"), ("ca", "Districte de Ghanzi"), ("ccp", "𑄊𑄚\u{11134}𑄎\u{11128}"), ("ceb", "Ghanzi District"), ("da", "Ghanzi District"), ("de", "Ghanzi District"), ("el", "Περιφέρεια Γκάνζι"), ("en", "Ghanzi"), ("es", "Ghanzi"), ("eu", "Ghanzi"), ("fa", "منطقه قانزی"), ("fi", "Ghanzi"), ("fr", "District de Ghanzi"), ("gu", "ઘા\u{a82}ઝી જિલ\u{acd}લો"), ("hi", "घनजी जिला"), ("id", "Distrik Ghanzi"), ("it", "distretto di Ghanzi"), ("ja", "ハンツィ地区"), ("ka", "განზი"), ("kn", "ಖಾನ\u{ccd}ಜ\u{cbf} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "간지 구"), ("lt", "Ganzio rajonas"), ("lv", "Ganzi distrikts"), ("mk", "Ганзи"), ("mr", "घनझी जिल\u{94d}हा"), ("ms", "Ghanzi District"), ("nb", "Ghanzi"), ("nl", "Ghanzi"), ("no", "Ghanzi"), ("pl", "Dystrykt Ghanzi"), ("pt", "Ghanzi"), ("ro", "Districtul Ghanzi"), ("ru", "Ганзи"), ("si", "ගන\u{dca}ස\u{dd2} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Ghanzi"), ("ta", "கண\u{bcd}ஜி ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "ఘ\u{c3e}ంజ\u{c3f} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตกานจ\u{e34}"), ("tr", "Ghanzi Bölgesi"), ("uk", "Ганзі"), ("ur", "غانزی ضلع"), ("vi", "Quận Ghanzi"), ("zh", "杭濟區")]),
                        unofficial_name_list: ["Ghansi", "Khanzi"].to_vec(),
                    }
                ),
                (
                    "JW",
                    Subdivision{
                        name: "Jwaneng",
                        country_alpha2: Alpha2::BW,
                        code: "JW",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Town,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Jwaneng"), ("ar", "غوانينغ"), ("az", "Cvanenq"), ("bn", "জোওনেং"), ("ca", "Jwaneng"), ("ccp", "𑄎\u{11133}𑄝\u{11127}𑄚𑄬\u{11101}"), ("ceb", "Jwaneng"), ("da", "Jwaneng"), ("de", "Jwaneng"), ("el", "Τζουανένγκ"), ("en", "Jwaneng"), ("es", "Jwaneng"), ("fa", "یواننگ، بوتسوانا"), ("fi", "Jwaneng"), ("fr", "Jwaneng"), ("gu", "જ\u{acd}વાન\u{ac7}\u{a82}ગ"), ("hi", "ज\u{94d}वान\u{947}\u{902}ग"), ("id", "Jwaneng"), ("it", "Jwaneng"), ("ja", "ジュワネン"), ("kn", "ಜ\u{ccd}ವಾಂಗ\u{ccd}ಂಗ\u{ccd}"), ("ko", "주아넹"), ("lt", "Džvanengas"), ("lv", "Džavanenga"), ("mr", "ज\u{941}वान\u{947}\u{902}ग"), ("ms", "Jwaneng"), ("nb", "Jwaneng"), ("nl", "Jwaneng"), ("no", "Jwaneng"), ("pl", "Jwaneng"), ("pt", "Jwaneng"), ("ro", "Jwaneng"), ("ru", "Джваненг"), ("si", "ජෙවන\u{dca}නේන\u{dca}ග\u{dca}"), ("sv", "Jwaneng"), ("ta", "ஜவ\u{bbe}னிங\u{bcd}"), ("te", "జ\u{c4d}వ\u{c3e}న\u{c46}ంగ\u{c4d}"), ("th", "จวาเนง"), ("tr", "Jwaneng"), ("uk", "Джваненг"), ("ur", "جوانینگ"), ("vi", "Jwaneng"), ("zh", "朱瓦能")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "KG",
                    Subdivision{
                        name: "Kgalagadi",
                        country_alpha2: Alpha2::BW,
                        code: "KG",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-24.7550285), longitude: Some(21.8568586), max_latitude: Some(-23.277603), min_latitude: Some(-26.9072461), max_longitude: Some(24.4867379), min_longitude: Some(19.999615)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Kgalagadi distrik"), ("ar", "مقاطعة كغالاجادي"), ("be", "Акруга Кгалагадзі"), ("bg", "Област Кгалагади"), ("bn", "কগ\u{9be}ল\u{9be}গ\u{9be}ডি জেল\u{9be}"), ("ca", "Districte de Kgalagadi"), ("ccp", "𑄉𑄣𑄉𑄓\u{11128}"), ("ceb", "Kgalagadi District"), ("da", "Kgalagadi District"), ("de", "Kgalagadi District"), ("el", "Περιφέρεια Κγκαλαγκάντι"), ("en", "Kgalagadi"), ("es", "Kgalagadi"), ("eu", "Kgalagadi"), ("fa", "منطقه کگالاگادی"), ("fi", "Kgalagadi"), ("fr", "District de Kgalagadi"), ("gu", "કગાલાગાદી જિલ\u{acd}લો"), ("hi", "कगालगाड\u{93c}ी जिला"), ("hy", "Կգալագադի"), ("id", "Distrik Kgalagadi"), ("it", "distretto di Kgalagadi"), ("ja", "カラハリ地区"), ("ka", "კგალაგადი"), ("kn", "ಕಲಾಗಗಡ\u{cbf} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "크갈라가디 구"), ("lt", "Kgalagadžio rajonas"), ("lv", "Khalahadi distrikts"), ("mk", "Кгалагади"), ("mr", "कागलगडी जिल\u{94d}हा"), ("ms", "Kgalagadi District"), ("nb", "Kgalagadi"), ("nl", "Kgalagadi"), ("no", "Kgalagadi"), ("pl", "Dystrykt Kgaladi"), ("pt", "Kgalagadi"), ("ro", "Districtul Kgalagadi"), ("ru", "Кгалагади"), ("si", "ක\u{dca}ගලග\u{dcf}ඩ\u{dd2} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Kgalagadi"), ("ta", "ககளகடி ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "క\u{c46}గ\u{c3e}లగడ\u{c3f} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตคาลากาด\u{e35}"), ("tr", "Kgalagadi Bölgesi"), ("uk", "Кгалагаді"), ("ur", "کگالاگادی ضلع"), ("vi", "Quận Kgalagadi"), ("zh", "卡拉哈迪區")]),
                        unofficial_name_list: ["Kgalagadi"].to_vec(),
                    }
                ),
                (
                    "KL",
                    Subdivision{
                        name: "Kgatleng",
                        country_alpha2: Alpha2::BW,
                        code: "KL",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-24.1970445), longitude: Some(26.2304616), max_latitude: Some(-23.5624137), min_latitude: Some(-24.6919435), max_longitude: Some(26.9604493), min_longitude: Some(25.9028879)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Kgatleng distrik"), ("ar", "مقاطعة كغاتلنغ"), ("be", "Акруга Кгатленг"), ("bg", "Област Кгатленг"), ("bn", "ঘ\u{9be}লেং জেল\u{9be}"), ("ca", "Districte de Kgatleng"), ("ccp", "𑄉𑄖\u{11134}𑄣𑄬\u{11101}"), ("ceb", "Kgatleng District"), ("da", "Kgatleng District"), ("de", "Kgatleng District"), ("el", "Περιφέρεια Κγκατλένγκ"), ("en", "Kgatleng"), ("es", "Kgatleng"), ("eu", "Kgatleng"), ("fa", "ناحیه کگاتلنگ"), ("fi", "Kgatleng"), ("fr", "District de Kgatleng"), ("gu", "ક\u{ac7}ગાટલ\u{ac7}\u{a82}ગ જિલ\u{acd}લો"), ("hi", "ग\u{948}टल\u{947}\u{902}ग जिला"), ("hy", "Կգատլենգ"), ("id", "Distrik Kgatleng"), ("it", "distretto di Kgatleng"), ("ja", "カトレン地区"), ("ka", "კგატლენგი"), ("kn", "ಕ\u{cc6}ಗ\u{ccd}ಲಾಂಗ\u{ccd} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "크가틀렝 구"), ("lt", "Kgatlengo rajonas"), ("lv", "Khatlenas distrikts"), ("mk", "Кгатленг"), ("mr", "किगटा\u{901}ग जिल\u{94d}हा"), ("ms", "Kgatleng District"), ("nb", "Kgatleng"), ("nl", "Kgatleng"), ("no", "Kgatleng"), ("pl", "Dystrykt Kgatleng"), ("pt", "Kgatleng"), ("ro", "Districtul Kgatleng"), ("ru", "Кгатленг"), ("si", "ක\u{dca}ගට\u{dca}ලෙන\u{dca}ග\u{dca} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Kgatleng"), ("ta", "க\u{bcd}கடலேங\u{bcd} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "గ\u{c3e}ట\u{c4d}ల\u{c46}ంగ\u{c4d} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตคกาทเลนจ\u{e4c}"), ("tr", "Kgatleng Bölgesi"), ("uk", "Кгатленг"), ("ur", "کگاٹلینگ ضلع"), ("vi", "Quận Kgatleng"), ("zh", "卡特倫區")]),
                        unofficial_name_list: ["Kgatleng"].to_vec(),
                    }
                ),
                (
                    "KW",
                    Subdivision{
                        name: "Kweneng",
                        country_alpha2: Alpha2::BW,
                        code: "KW",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-23.8367249), longitude: Some(25.2837585), max_latitude: Some(-22.955476), min_latitude: Some(-24.7757569), max_longitude: Some(26.0196919), min_longitude: Some(22.9627589)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Kweneng distrik"), ("ar", "مقاطعة كويننغ"), ("be", "Акруга Квененг"), ("bg", "Куененг"), ("bn", "কেনেং জেল\u{9be}"), ("ca", "Districte de Kweneng"), ("ccp", "𑄇\u{1112a}𑄠𑄬𑄚𑄬\u{11101}"), ("ceb", "Kweneng District"), ("da", "Kweneng"), ("de", "Kweneng District"), ("el", "Περιφέρεια Κουενένγκ"), ("en", "Kweneng"), ("es", "Kweneng"), ("eu", "Kweneng"), ("fa", "منطقه کوئننگ"), ("fi", "Kweneng"), ("fr", "District de Kweneng"), ("gu", "ક\u{acd}વાન\u{ac7}\u{a82}ગ જિલ\u{acd}લો"), ("hi", "क\u{94d}व\u{947}न\u{947}\u{902}ग जिला"), ("id", "Distrik Kweneng"), ("it", "distretto di Kweneng"), ("ja", "クウェネン地区"), ("ka", "კვენენგი"), ("kn", "ಕ\u{ccd}ವ\u{cc6}ನ\u{cc6}ಂಗ\u{ccd} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "퀘넹 구"), ("lt", "Kvenengo rajonas"), ("lv", "Kvenenas distrikts"), ("mk", "Квененг"), ("mr", "क\u{94d}व\u{947}न\u{947}न\u{94d}ग जिल\u{94d}हा"), ("ms", "Kweneng District"), ("nb", "Kweneng"), ("nl", "Kweneng"), ("no", "Kweneng"), ("pl", "Dystrykt Kweneng"), ("pt", "Kweneng"), ("ro", "Districtul Kweneng"), ("ru", "Квененг"), ("si", "ක\u{dca}වෙනේන\u{dca}ග\u{dca} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Kweneng"), ("ta", "கேனெங\u{bcd} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "క\u{c4d}వ\u{c46}న\u{c46}ంగ\u{c4d} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตคเวเนง"), ("tr", "Kweneng Bölgesi"), ("uk", "Квененг"), ("ur", "کوینینگ ضلع"), ("vi", "Quận Kweneng"), ("zh", "奎嫩區")]),
                        unofficial_name_list: ["Kweneng"].to_vec(),
                    }
                ),
                (
                    "LO",
                    Subdivision{
                        name: "Lobatse",
                        country_alpha2: Alpha2::BW,
                        code: "LO",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Town,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Lobatse"), ("ar", "لوباتس"), ("bg", "Лобаце"), ("bn", "লোব\u{9be}ৎসে"), ("ca", "Lobatse"), ("ccp", "𑄢\u{11127}𑄝𑄖\u{11134}𑄥𑄬"), ("ceb", "Lobatse"), ("da", "Lobatse"), ("de", "Lobatse"), ("el", "Λομπάτσε"), ("en", "Lobatse"), ("es", "Lobatse"), ("et", "Lobatse"), ("fa", "لوباتس، بوتسوانا"), ("fi", "Lobatse"), ("fr", "Lobatse"), ("gu", "લોબ\u{ac7}ટ\u{acd}સ"), ("hi", "लोबात\u{94d}स\u{947}"), ("hr", "Lobatse"), ("hu", "Lobatse"), ("id", "Lobatse"), ("it", "Lobatse"), ("ja", "ロバツェ"), ("kn", "ಲ\u{cca}ಬಾಟ\u{ccd}ಸ\u{cc6}"), ("ko", "로바체"), ("lt", "Lobatsė"), ("lv", "Lobatse"), ("mr", "लोब\u{947}ट\u{947}"), ("ms", "Lobatse"), ("nb", "Lobatse"), ("nl", "Lobatse"), ("no", "Lobatse"), ("pl", "Lobatse"), ("pt", "Lobatse"), ("ro", "Lobatse"), ("ru", "Лобаце"), ("si", "ලොබට\u{dca}සේ"), ("sv", "Lobatse"), ("ta", "லோபட\u{bcd}ஸ\u{bcd}"), ("te", "ల\u{c4b}బ\u{c3e}ట\u{c4d}స\u{c47}"), ("th", "เม\u{e37}องโลบ\u{e31}ตเซ"), ("tr", "Lobatse"), ("uk", "Лобаце"), ("ur", "لوباٹسے"), ("vi", "Lobatse"), ("zh", "洛巴策")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "NE",
                    Subdivision{
                        name: "North-East",
                        country_alpha2: Alpha2::BW,
                        code: "NE",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-20.9030555), longitude: Some(27.4556388), max_latitude: Some(-20.473381), min_latitude: Some(-21.571556), max_longitude: Some(28.013578), min_longitude: Some(27.2119901)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Noord-Oos distrik, Botswana"), ("ar", "مقاطعة الشمال الشرقي"), ("be", "Паўночна-усходняя акруга, Батсвана"), ("bn", "নর\u{9cd}থ-ইস\u{9cd}ট জেল\u{9be}"), ("ca", "Districte del Nord-est"), ("ccp", "𑄅\u{1112a}𑄖\u{11133}𑄦\u{11127}𑄢\u{11134} 𑄛\u{1112a}𑄇\u{11134}"), ("ceb", "North East District (distrito sa Botswana)"), ("da", "North-East District"), ("de", "North-East District"), ("el", "Βορειοανατολική Περιφέρεια"), ("en", "North East"), ("es", "Distrito Noreste"), ("eu", "Ipar-ekialdea"), ("fa", "ناحیه شمال شرقی (بوتسوانا)"), ("fi", "North-East District"), ("fr", "District du Nord-Est"), ("gu", "ઉત\u{acd}તર-પ\u{ac2}ર\u{acd}વ જિલ\u{acd}લો"), ("hi", "उत\u{94d}तर-प\u{942}र\u{94d}व जिला"), ("id", "Distrik Timur Laut, Botswana"), ("it", "distretto Nordorientale"), ("ja", "ノースイースト地区"), ("ka", "ჩრდილო-აღმოსავლეთის ოლქი"), ("kn", "ಈಶಾನ\u{ccd}ಯ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "북동부 구"), ("lt", "Šiaurės rytų rajonas"), ("lv", "Ziemeļaustrumu distrikts"), ("mk", "Североисточен округ"), ("mr", "प\u{942}र\u{94d}व-प\u{942}र\u{94d}व जिल\u{94d}हा"), ("ms", "North-East District"), ("nb", "North-East"), ("nl", "North-East"), ("no", "North-East"), ("pl", "Dystrykt Północno-Wschodni"), ("pt", "Nordeste"), ("ro", "Districtul North-East, Botswana"), ("ru", "Северо-Восточный округ"), ("si", "උත\u{dd4}ර\u{dd4} නැගෙනහ\u{dd2}ර ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Northeast"), ("ta", "வடக\u{bcd}கு -கிழக\u{bcd}கு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "ఈశ\u{c3e}న\u{c4d}య జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "ซาเรมา"), ("tr", "Kuzeydoğu Bölgesi"), ("uk", "Північно-Східний округ"), ("ur", "شمال-مشرقی ضلع"), ("vi", "Quận Đông-Bắc"), ("zh", "東北區")]),
                        unofficial_name_list: ["North-East"].to_vec(),
                    }
                ),
                (
                    "NW",
                    Subdivision{
                        name: "North-West",
                        country_alpha2: Alpha2::BW,
                        code: "NW",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-19.1905321), longitude: Some(23.0011989), max_latitude: Some(-17.780813), min_latitude: Some(-21.0002549), max_longitude: Some(25.9879499), min_longitude: Some(20.9969499)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Noord-Wes distrik, Botswana"), ("ar", "مقاطغة شمال غرب"), ("be", "Паўночна-заходняя акруга, Батсвана"), ("bg", "Северозападна област"), ("bn", "নর\u{9cd}থ ওয\u{9bc}েস\u{9cd}ট জেল\u{9be}"), ("ca", "Districte del Nord-oest"), ("ccp", "𑄅\u{1112a}𑄖\u{11133}𑄦\u{11127}𑄢\u{11134} 𑄛\u{11127}𑄏\u{11128}𑄟\u{11134}"), ("ceb", "North West District"), ("da", "North-West District"), ("de", "North West District"), ("el", "Βορειοδυτική Περιφέρεια"), ("en", "North West"), ("es", "Distrito Noroeste"), ("eu", "Ipar-mendebaldea"), ("fa", "ناحیه شمال غربی (بوتسوانا)"), ("fi", "North-West District"), ("fr", "District du Nord-Ouest"), ("gu", "ઉત\u{acd}તર-પશ\u{acd}ચિમ જિલ\u{acd}લો"), ("hi", "उत\u{94d}तर-पश\u{94d}चिमी जिला (बोत\u{94d}सवाना)"), ("id", "Distrik Barat Laut, Botswana"), ("it", "distretto Nordoccidentale"), ("ja", "ノースウェスト地区"), ("ka", "ჩრდილო-დასავლეთის ოლქი"), ("kn", "ವಾಯುವ\u{ccd}ಯ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "북서부 구"), ("lt", "Šiaurės vakarų rajonas"), ("lv", "Ziemeļrietumu distrikts"), ("mk", "Северозападен округ"), ("mr", "उत\u{94d}तर-पश\u{94d}चिम जिल\u{94d}हा"), ("ms", "North-West District"), ("nb", "North-West"), ("nl", "North-West"), ("no", "North-West"), ("pl", "Dystrykt Północno-Zachodni"), ("pt", "Noroeste"), ("ro", "Districtul North-West, Botswana"), ("ru", "Северо-Западный округ"), ("si", "වයඹ ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Northwest"), ("ta", "வடக\u{bcd}கு -மேற\u{bcd}கு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "న\u{c3e}ర\u{c4d}త\u{c4d}-వ\u{c46}స\u{c4d}ట\u{c4d} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตนอร\u{e4c}ท เวส"), ("tr", "Kuzeybatı Bölgesi"), ("uk", "Північно-Західний округ"), ("ur", "شمال-مغربی ضلع"), ("vi", "Quận Tây-Bắc"), ("zh", "西北區")]),
                        unofficial_name_list: ["North-West"].to_vec(),
                    }
                ),
                (
                    "SE",
                    Subdivision{
                        name: "South-East",
                        country_alpha2: Alpha2::BW,
                        code: "SE",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-24.9366094), longitude: Some(25.8048521), max_latitude: Some(-24.511588), min_latitude: Some(-25.4709631), max_longitude: Some(26.1813639), min_longitude: Some(25.5438541)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Suid-Oos distrik, Botswana"), ("ar", "المقاطعة الجنوب شرقية"), ("be", "Паўднёва-усходняя акруга, Батсвана"), ("bg", "Югоизточна област"), ("bn", "স\u{9be}উথ ইস\u{9cd}ট জেল\u{9be}"), ("ca", "Districte del Sud-est"), ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{11134} 𑄛\u{1112a}𑄇\u{11134}"), ("ceb", "South East District"), ("da", "South-East District"), ("de", "South-East District"), ("el", "Νοτιοανατολική Περιφέρεια"), ("en", "South East"), ("es", "Distrito Sudeste"), ("eu", "Hego-ekialdea"), ("fa", "ناحیه جنوب شرقی"), ("fi", "South-East District"), ("fr", "District du Sud-Est"), ("gu", "દક\u{acd}ષિણ-પ\u{ac2}ર\u{acd}વ જિલ\u{acd}લો"), ("hi", "दक\u{94d}षिण-प\u{942}र\u{94d}व जिला"), ("id", "Distrik Tenggara, Botswana"), ("it", "distretto Sudorientale"), ("ja", "サウスイースト地区"), ("ka", "სამხრეთ-აღმოსავლეთის ოლქი"), ("kn", "ಆಗ\u{ccd}ನ\u{cc7}ಯ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "남동부 구"), ("lt", "Pietryčių rajonas"), ("lv", "Dienvidaustrumu distrikts"), ("mk", "Југоисточен округ"), ("mr", "दक\u{94d}षिण-प\u{942}र\u{94d}व जिल\u{94d}हा"), ("ms", "South-East District"), ("nb", "South-East"), ("nl", "South-East"), ("no", "South-East"), ("pl", "Dystrykt Południowo-Wschodni"), ("pt", "Sudeste"), ("ro", "Districtul South-East, Botswana"), ("ru", "Юго-Восточный округ"), ("si", "දක\u{dd4}ණ\u{dd4} නැගෙනහ\u{dd2}ර ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Southeast"), ("ta", "தெற\u{bcd}கு -கிழக\u{bcd}கு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "ఆగ\u{c4d}న\u{c47}య జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เซาท\u{e4c} อ\u{e35}ส ด\u{e34}สทร\u{e34}ค"), ("tr", "Güneydoğu Bölgesi"), ("uk", "Південно-Східний округ"), ("ur", "جنوب-مشرقی ضلع"), ("vi", "Quận Đông-Nam"), ("zh", "東南區")]),
                        unofficial_name_list: ["South-East"].to_vec(),
                    }
                ),
                (
                    "SO",
                    Subdivision{
                        name: "Southern",
                        country_alpha2: Alpha2::BW,
                        code: "SO",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(-24.823384), longitude: Some(24.7142918), max_latitude: Some(-23.9969671), min_latitude: Some(-25.8257559), max_longitude: Some(25.693459), min_longitude: Some(23.048267)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Suid distrik, Botswana"), ("ar", "المقاطعة الجنوبية"), ("az", "Cənubi dairə"), ("be", "Паўднёвая акруга, Батсвана"), ("bg", "Южна област"), ("bn", "স\u{9be}উদ\u{9be}র\u{9cd}ন জেল\u{9be}"), ("ca", "Districte del Sud"), ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{1112e}𑄘\u{11128}"), ("ceb", "Southern District"), ("da", "Southern District"), ("de", "Southern District"), ("el", "Νότια Περιφέρεια"), ("en", "Southern"), ("es", "Distrito Sur"), ("eu", "Hegoaldea"), ("fa", "بخش جنوبی (بوتسوانا)"), ("fi", "Southern District"), ("fr", "District du Sud"), ("gu", "દક\u{acd}ષિણી જિલ\u{acd}લો"), ("hi", "दक\u{94d}षिणी जिला (बोत\u{94d}स\u{94d}वाना"), ("id", "Distrik Selatan, Botswana"), ("it", "distretto Meridionale"), ("ja", "サザン地区"), ("ka", "სამხრეთის ოლქი"), ("kn", "ದಕ\u{ccd}ಷ\u{cbf}ಣ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "남부 구"), ("lt", "Pietų rajonas"), ("lv", "Dienvidu distrikts"), ("mk", "Јужен округ"), ("mr", "दक\u{94d}षिणी जिल\u{94d}हा"), ("ms", "Southern District"), ("nb", "Southern"), ("nl", "Southern"), ("no", "Southern"), ("pl", "Dystrykt Południowy"), ("pt", "Distrito do Sul"), ("ro", "Districtul Southern, Botswana"), ("ru", "Южный округ"), ("si", "දක\u{dd4}ණ\u{dd4} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Southern"), ("ta", "தெற\u{bcd}கு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "దక\u{c4d}ష\u{c3f}ణ జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตภาคใต\u{e49} (บอตสวานา)"), ("tr", "Güney Bölgesi"), ("uk", "Південний округ"), ("ur", "سدرن ضلع"), ("vi", "Quận Miền Nam"), ("zh", "南部區")]),
                        unofficial_name_list: ["Southern"].to_vec(),
                    }
                ),
                (
                    "SP",
                    Subdivision{
                        name: "Selibe Phikwe",
                        country_alpha2: Alpha2::BW,
                        code: "SP",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Town,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Selebi-Phikwe"), ("ar", "سيليبي-فيكوي"), ("bn", "সেলেবি-পিখবে"), ("ca", "Selebi-Phikwe"), ("ccp", "𑄥𑄬𑄣\u{11128}𑄝𑄬 𑄜\u{11128}𑄇\u{1112e}𑄠𑄬"), ("ceb", "Selebi-Phikwe"), ("da", "Selebi-Phikwe"), ("de", "Selebi-Phikwe"), ("el", "Σελέμπι-Φίκουε"), ("en", "Selibe Phikwe"), ("es", "Selebi-Phikwe"), ("eu", "Selebi-Phikwe"), ("fa", "سلیب فیکوه، بوتسوانا"), ("fi", "Selebi-Pikwe"), ("fr", "Selebi-Phikwe"), ("gu", "સ\u{ac7}લ\u{ac7}બી-ફિકવ\u{ac7}"), ("hi", "स\u{947}ल\u{947}बी-फिकव\u{947}"), ("hr", "Selebi-Phikwe"), ("id", "Selebi-Phikwe"), ("it", "Selebi Pikwe"), ("ja", "セレビ・ピクウェ"), ("kn", "ಸ\u{cc6}ಲ\u{cc6}ಬ\u{cbf}-ಫ\u{cbf}ಕ\u{ccd}ವ\u{cc6}"), ("ko", "셀레비피퀘"), ("lt", "Selebi Pikvė"), ("lv", "Selebi-Phikve"), ("mr", "स\u{947}लीबी-फिक\u{94d}व\u{947}"), ("ms", "Selebi-Phikwe"), ("nb", "Selebi-Phikwe"), ("nl", "Selebi-Phikwe"), ("no", "Selebi-Phikwe"), ("pl", "Selebi-Pikwe"), ("pt", "Selebi-Phikwe"), ("ro", "Selibe Phikwe"), ("ru", "Селеби-Пхикве"), ("si", "සෙලෙබ\u{dd2}-ප\u{dd2}ක\u{dca}වේ"), ("sv", "Selebi-Phikwe"), ("ta", "செலிபி-பிக\u{bcd}வெ"), ("te", "స\u{c46}ల\u{c46}బ\u{c3f}-ఫ\u{c3f}క\u{c4d}వ\u{c47}"), ("th", "เซเลบ\u{e34} พค\u{e34}คว\u{e35}"), ("tr", "Selibe-Phikwe"), ("uk", "Селебі-Пхікве"), ("ur", "سیلیبی-فیکوے"), ("vi", "Selebi-Phikwe"), ("zh", "塞莱比-皮奎")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "ST",
                    Subdivision{
                        name: "Sowa Town",
                        country_alpha2: Alpha2::BW,
                        code: "ST",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Town,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("af", "Sowa, Botswana"), ("ar", "سوا، بوتسوانا"), ("bn", "সোব\u{9be}, বতসোয\u{9bc}\u{9be}ন\u{9be}"), ("ca", "Sowa"), ("ccp", "𑄥\u{11131} 𑄑𑄅\u{1112a}𑄚\u{11134}"), ("da", "Sowa, Botswana"), ("de", "Sowa"), ("el", "Σόβα, Μποτσβάνα"), ("en", "Sowa Town"), ("es", "Ciudad del Sowa"), ("fi", "Sowa, Botswana"), ("fr", "Sowa Town"), ("gu", "સોવા, બોત\u{acd}સવાના"), ("hi", "सोवा, बोत\u{94d}सवाना"), ("id", "Sowa, Botswana"), ("it", "Sowa Town"), ("ja", "ソワ"), ("kn", "ಸ\u{cca}ವಾ, ಬ\u{cca}ಟ\u{ccd}ಸ\u{ccd}ವಾನಾ"), ("ko", "소와, 보츠와나"), ("lt", "Sova, Botsvana"), ("lv", "Sova, Botsvana"), ("mr", "सोवा, बोत\u{94d}सवाना"), ("ms", "Sowa, Botswana"), ("nb", "Sowa"), ("nl", "Sowa, Botswana"), ("no", "Sowa"), ("pl", "Sowa, Botswana"), ("pt", "Sowa, Botswana"), ("ro", "Sowa, Botswana"), ("ru", "Сова"), ("si", "සොව\u{dcf} බොට\u{dca}ස\u{dca}ව\u{dcf}න\u{dcf}"), ("sv", "Sowa Town"), ("ta", "சோவ\u{bbe} , போட\u{bcd}ஸ\u{bcd}வ\u{bbe}ன\u{bbe}"), ("te", "స\u{c4b}వ\u{c3e}, బ\u{c4b}త\u{c4d}స\u{c4d}వ\u{c3e}న\u{c3e}"), ("th", "โซวา บอตสวานา"), ("tr", "Sowa, Botswana"), ("uk", "Сова"), ("ur", "سووا"), ("vi", "Sowa, Botswana")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
            ]

        )
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, DistanceUnit, Region, SubRegion, VatRates,
    WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "bw")]
/// [`Country`](crate::Country) struct for this country.
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::BW,
        alpha3: Alpha3::BWA,
        address_format: None,
        continent: Continent::Africa,
        country_code: 267,
        currency_code: CurrencyCode::BWP,
        maybe_gec: Some(GEC::BC),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        maybe_ioc: Some(IOC::BOT),
        iso_long_name: "The Republic of Botswana",
        iso_short_name: "Botswana",
        official_language_list: ["en", "tn"].to_vec(),
        spoken_language_list: ["en", "tn"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [7].to_vec(),
        national_prefix: "None",
        maybe_nationality: Some("Motswana"),
        maybe_vehicle_registration_code: Some("RB"),
        number: "072",
        postal_code: false,
        postal_code_format: None,
        maybe_region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        maybe_subregion: Some(SubRegion::SouthernAfrica),
        un_locode: "BW",
        unofficial_name_list: ["Botswana", "ボツワナ"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "emojis")]
        emoji: "🇧🇼",
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Botswana"),
            ("af", "Botswana"),
            ("ak", "Botswana"),
            ("am", "Botswana"),
            ("an", "Botswana"),
            ("ar", "بوتسوانا"),
            ("as", "বটছোৱ\u{9be}ন\u{9be}"),
            ("ay", "Botswana"),
            ("az", "Botsvana"),
            ("ba", "Botswana"),
            ("be", "Батсвана"),
            ("bg", "Ботсуана"),
            ("bi", "Botswana"),
            ("bn", "বোটসওয়\u{9be}ন\u{9be}"),
            ("bn_IN", "বোটসওয়\u{9be}ন\u{9be}"),
            ("br", "Botswana"),
            ("bs", "Bocvana"),
            ("ca", "Botswana"),
            ("ce", "Ботсвана"),
            ("ch", "Botswana"),
            ("cs", "Botswana"),
            ("cv", "Ботсвана"),
            ("cy", "Botswana"),
            ("da", "Botswana"),
            ("de", "Botsuana"),
            ("dv", "ބ\u{7ae}ޓ\u{7aa}ސ\u{7b0}ވ\u{7a7}ނ\u{7a7}"),
            ("dz", "བ\u{f71}\u{f7c}ཊས\u{f72}་ཝ་ན།"),
            ("ee", "Botswana"),
            ("el", "Μποτσουάνα"),
            ("en", "Botswana"),
            ("eo", "Bocvano"),
            ("es", "Botsuana"),
            ("et", "Botswana"),
            ("eu", "Botswana"),
            ("fa", "بوتسوانا"),
            ("ff", "Botswana"),
            ("fi", "Botswana"),
            ("fo", "Botsvana"),
            ("fr", "Botswana"),
            ("fy", "Botswana"),
            ("ga", "An Bhotsuáin"),
            ("gl", "Botsuana"),
            ("gn", "Botswana"),
            ("gu", "બોટ\u{acd}સ\u{acd}વાના"),
            ("gv", "Yn Votswaan"),
            ("ha", "Botswana"),
            ("he", "בוטסואנה"),
            ("hi", "बोत\u{94d}सवाना"),
            ("hr", "Bocvana"),
            ("ht", "Botswana"),
            ("hu", "Botswana"),
            ("hy", "Բոտսվանա"),
            ("ia", "Botswana"),
            ("id", "Botswana"),
            ("io", "Botswana"),
            ("is", "Botsvana"),
            ("it", "Botswana"),
            ("iu", "Botswana"),
            ("ja", "ボツワナ"),
            ("ka", "ბოტსვანა"),
            ("ki", "Botswana"),
            ("kk", "Ботсвана"),
            ("kl", "Botswana"),
            ("km", "ប\u{17bb}តស\u{17d2}វាណា"),
            ("kn", "ಬ\u{ccb}ಟ\u{ccd}ಸ\u{ccd}\u{200d}ವಾನಾ"),
            ("ko", "보츠와나"),
            ("ku", "Botswana"),
            ("kv", "Botswana"),
            ("kw", "Botswana"),
            ("ky", "Ботсвана"),
            ("lo", "Botswana"),
            ("lt", "Botsvana"),
            ("lv", "Botsvana"),
            ("mi", "Botswana"),
            ("mk", "Боцвана"),
            ("ml", "ബോട\u{d4d}സ\u{d4d}വ\u{d3e}ന"),
            ("mn", "Ботсвана"),
            ("mr", "बोस\u{94d}वाना"),
            ("ms", "Botswana"),
            ("mt", "Botswana"),
            (
                "my",
                "ဘော\u{1037}ဆ\u{103d}ာနာန\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Botwana"),
            ("nb", "Botswana"),
            ("ne", "बोट\u{94d}सवाना"),
            ("nl", "Botswana"),
            ("nn", "Botswana"),
            ("nv", "Tswana Dineʼé Bikéyah"),
            ("oc", "Botswana"),
            ("or", "ବୋସ\u{b4d}ତ\u{b4d}ବ\u{b3e}ନ\u{b3e}"),
            ("pa", "ਬ\u{a42}ਟਸਵਾਨਾ"),
            ("pi", "बोत\u{94d}सवाना"),
            ("pl", "Botswana"),
            ("ps", "بوتسوانا"),
            ("pt", "Botsuana"),
            ("pt_BR", "Botsuana"),
            ("ro", "Botswana"),
            ("ru", "Ботсвана"),
            ("rw", "Botswana"),
            ("sc", "Botswana"),
            ("sd", "Botswana"),
            ("si", "බොට\u{dca}ස\u{dca}ව\u{dcf}න\u{dcf}"),
            ("sk", "Botswana"),
            ("sl", "Bocvana"),
            ("so", "Botswana"),
            ("sq", "Botsvanë"),
            ("sr", "Боцвана"),
            ("sv", "Botswana"),
            ("sw", "Botswana"),
            ("ta", "போட\u{bcd}ஸ\u{bcd}வ\u{bbe}ன\u{bbe}"),
            ("te", "బ\u{c4b}స\u{c4d}వ\u{c3e}న\u{c3e}"),
            ("tg", "Ботсвана"),
            ("th", "บอตสวานา"),
            ("ti", "ቦትስዋና"),
            ("tk", "Botswana"),
            ("tl", "Botswana"),
            ("tr", "Botsvana"),
            ("tt", "Боцвана"),
            ("ug", "بوتسۋانا"),
            ("uk", "Ботсвана"),
            ("ur", "بوٹسوانا"),
            ("uz", "Botsvana"),
            ("ve", "Vhu-Tswana"),
            ("vi", "Bốt-xoă-na"),
            ("wa", "Boswana"),
            ("wo", "Botswana"),
            ("xh", "Botswana"),
            ("yo", "Bòtswánà"),
            ("zh_CN", "博兹瓦那"),
            ("zh_HK", "博茨瓦納"),
            ("zh_TW", "波札那"),
            ("zu", "IButswana"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
        g7_member: false,
        g20_member: false,
        eu_member: false,
        un_member: true,
        eea_member: false,
        maybe_vat_rates: None,
        distance_unit: DistanceUnit::Km,
        maybe_population: Some(2630296),
    }
}
